name: Nihai Savaş Odası Otomasyonu

on:
  schedule:
    # Her hafta içi sabah 09:55'te çalışır (UTC saatine göre ayarlanır)
    - cron: '25 6 * * 1-5'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Bağımlılıkları Yükle
        run: pip install requests

      - name: Botu Çalıştır
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py
